### ISSUE TITLE
Integrate the functions files deeper into morpho

### ISSUE THREAD

**Issue by guiguem** [project8/morpho#13]
Currently the functions files are located in the morpho repo and one has to point to them in the script used for configuring morpho: one defines the absolute (or relative) path to the folder containing the files under `stan.model.function_files_location` parameter
This should be ok when submitting a job, but one has to send them in the job submission.
If possible, we would like to have this file integrated to morpho, such as the number of files to send is reduced.

**Comment by laroque** [comment]
Sorry if this isn't helpful, I've not really looked at the morpho source. 

You may want to look at dripline_agent in dragonfly/subcommands, and specifically the way that modules are searched when specifying objects in configuration files. There, the objects in dripline and dragonfly are recognized automatically if recognized, but a local source can also be specified. 

Under that model, one could have 'standard' functions implemented in the core package and also allow the user to provide a custom function file (which is uploaded in the dirac submission) if they want to try something new.

The expected model in the slow control was that local things would be easier for early testing/development, and that anything useful would eventually get migrated into the official code base. In practice I think that this feature has be very rarely used.

**Comment by guiguem** [comment]
Well the Stan 'functions' files are located in morpho/functions and look like that:
```
real hydrogen_atomic_mass() {return  1.00794 * unit_mass();}
```
Clearly not a python thing, but maybe python can actually save them the files when installing morpho.
Not sure which part of dripline_agent you are referring too, but I will have a closer look tomorrow...

**Comment by guiguem** [comment]
If https://github.com/project8/morpho/issues/10 is solved, we should be able to add the complete path to the morpho source file as a command line and then morpho will look for the functions from there...

**Comment by guiguem** [comment]
I guess the functions files should be moved to the script repo too, since they are kind of part of the model one wants to use, morpho been more a wrapper than a model container...
We then need to merge all these files into the script repo and fill the stan.model.functions_files_locations field in the config files (or use the in-command-line technique).

**Comment by guiguem** [comment]
The move of the functions into the scripts repo has been done.
