### ISSUE TITLE
Automatically create cache and results folder

### ISSUE THREAD

**Issue by guiguem** [project8/morpho#16]
Morpho does not try to see if these folders exist before trying to create output files in them.
We should solve that by checking the existence of the folders we try to use and create them if the don't exist.

**Comment by taliaweiss** [comment]
Could we address this by incorporating something like the following into the stan_cache function in morpho/bin/morpho, after cache_fn is defined (line 209)?

dir = os.path.dirname(cache_fn)
if not os.path.exists(dir):
        os.makedirs(dir)

We could then do something similar for the results folder. (By replacing "cache_fn" in the code above with "ofilename" from the write_result function?) Code based off of: http://stackoverflow.com/questions/273192/how-to-check-if-a-directory-exists-and-create-it-if-necessary

Are there additional subtleties that would make this more tricky?

**Comment by guiguem** [comment]
That was mainly the idea.

**Comment by taliaweiss** [comment]
This has been implemented in "develop."
