### ISSUE TITLE
Check a posteriori distributions with 2D plots

### ISSUE THREAD

**Issue by guiguem** [project8/morpho#19]
It might be interesting to have a plotting scripts which allows us to automatically display the 2D and 1D a posteriori distributions in order to look at the correlations and the shape of the distributions (Gaussian for example).

![untitled](https://cloud.githubusercontent.com/assets/16764756/23779866/e75911be-04f7-11e7-956c-46c25cd3bd1a.png)

**Comment by guiguem** [comment]
This link might be useful: even if it is for C++, we can very easily adapt it to python/ROOT and with an arbitrary number of 2D plots
https://root.cern.ch/root/html534/tutorials/hist/h2proj.C.html

**Comment by guiguem** [comment]
A preliminary working version exists: c10ae764f196cd74f21103f322714379d33c7d5e
It generates such figures: 
![amplitude_q_delta_energy___loglikelihood](https://cloud.githubusercontent.com/assets/16764756/26088430/0ad23b96-39ac-11e7-826b-2a9c1c2195f3.png)
Some cosmetic changes needs to be done.

**Comment by guiguem** [comment]
A newer version using the morpho_test model: the size of the canvas is manually changeable.
[can_900_12000_a_b_variance.pdf](https://github.com/project8/morpho/files/1005361/can_900_12000_a_b_variance.pdf)
A next step would be to add the projected histogram on the sides.

**Comment by joejohnston203** [comment]
1D histograms were added, with different shades for a distance 1 sigma from the mean and 1 sigma from the mean:
[aposteriori_morpho_test_a_b_variance.pdf](https://github.com/project8/morpho/files/1205752/aposteriori_morpho_test_a_b_variance.pdf)

A correlation factors plot was also included, that calculates the correlation factor for each pair of variables and represents it with a color. This is an easy way to see correlations when many variables are involved:
[corr_factors_morpho_test_a_b_variance.pdf](https://github.com/project8/morpho/files/1205754/corr_factors_morpho_test_a_b_variance.pdf)

morpho_linear_fit.yaml was updated to include the correlation factor plot.

Thesse updates are on the branch feature/aposteriori_1D_histograms:
https://github.com/project8/morpho/tree/feature/aposteriori_1D_histograms

**Comment by joejohnston203** [comment]
The intervals on the 1D histograms are currently centered around the mean, with width equal to multiples of the standard deviation. In the future, we could add the option to display other intervals, such as 68%/ 95% confidence levels.
