### ISSUE TITLE
Root files created by the data_reducer store python integers as floats

### ISSUE THREAD

**Issue by taliaweiss** [project8/morpho#21]
When we save the integers "nBinSpectrum" and "nBinTime" to a root file in lines 258-272 of data_reducer.py, the root file stores them as float_t values. It would be good to get the root file to store them as int_t values, so that our analyzer models will (hopefully) read them in as integers. 

Alternatively, we could find a way to make the analyzer models read in the root float_t values as integers, but I think that would prove tricky (especially as Stan does not allow for reals to be converted to integers).

**Comment by guiguem** [comment]
I think you could actually convert a float into a int by specifying the data_format when reading the data.
I agree we should try to save int from the very beginning though: instead of using TNtuple, we should create a proper tree with branches of int.
This is an extra step of complexity, but should be trivial to implement.

**Comment by taliaweiss** [comment]
That sounds good. Is it possible that we could also save minimum and maximum kinetic energies/frequencies in this new tree (even though those are floats)?

I think this would be a good idea because if we save the number of bins in the root file but type the wrong minimum or maximum energy/frequency into the analyzer config file, then the analyzer will think that the bin edges are in the wrong locations. If we save all three numbers into the root file, there won't be any mismatches when they are read into the analyzer.

**Comment by guiguem** [comment]
Yes, this is a good idea.
If we are going to have floats and int (which is ok) in the same tree, we should really use the data_format value in the config file: for example in my smeared_spectrum_.json I have:
```json
"name" : "./MassHierarchy/results/spectrum_generator_reduced_fake_NH.root",
"format" : "root",
"tree" : "spectrum",
"branches" : [
   {"name" : "KE_data", "stan_alias" : "KE_data"},
   {"name" : "n_spectrum_data", "stan_alias" : "n_spectrum_data", "data_format" : "integer"}
]
```

**Comment by guiguem** [comment]
I think this issue is done: the trick when we have integer in a tree inside a root file is to specify the data_format as integer (see above).
The default (when not specified) is float.
