### ISSUE TITLE
Smooth-edge flat prior

### ISSUE THREAD

**Issue by guiguem** [project8/morpho#25]
A true Heaviside function as prior is not very nice with Stan, because of the discontinuities.
We need to define a new prior function which provides continuous edges (L2 might be enough) and implement it in the functions folder in scripts.

**Comment by jformaggio** [comment]
What about using a butterworth?  It is smooth and somewhat reminiscent of the bandpass filter already there.

**Comment by guiguem** [comment]
That might be enough. 
What would be the order of the butterworth?

**Comment by guiguem** [comment]
A butterworth filter method has been added to the private functions directory: its amplitude is set to one and has two edges.
