### ISSUE TITLE
Save diagnostic 

### ISSUE THREAD

**Issue by guiguem** [project8/morpho#27]
It is interesting to have access to some diagnostic inputs after sampling a Likelihood.
We could use:
- [x] the divergence using an example given by Mike [here](https://github.com/project8/morpho/files/812373/Diagnosing.20Biased.20Inference.20with.20Divergences.pdf)
```divergent <- get_sampler_params(fit_cp99, inc_warmup=FALSE)[[1]][,'divergent__']```
This could be saved as a new tree within the result file (hdf5 or root).
- [x] saving the warmup part of each chains: when using the extract in the pyStanLoad, we can set an option to get the warmup chain. We could then add a integer branch in the tree of data telling whether a sample is  warmup or final sampling.
- [x] generate 2D scatter plots of the variables, by cutting on the divergence (either ==0 and ==1) in two different colors
- [x] save the delta Energy between two steps in the sampling and warmup
```
extract(pars=None, permuted=True, inc_warmup=False)
Extract samples in different forms for different parameters.

Parameters

pars : sequence of str
names of parameters (including other quantities)
permuted : bool
If True, returned samples are permuted. All chains are merged and warmup samples are discarded.
inc_warmup : bool
If True, warmup samples are kept; otherwise they are discarded. If permuted is True, inc_warmup is ignored.
Returns

samples : dict or array If permuted is True, return dictionary with samples for each parameter (or other quantity) named in pars.

If permuted is False, an array is returned. The first dimension of the array is for the iterations; the second for the number of chains; the third for the parameters. Vectors and arrays are expanded to one parameter (a scalar) per cell, with names indicating the third dimension. Parameters are listed in the same order as model_pars and flatnames.
```

There might be some other options we will need to consider.

**Comment by guiguem** [comment]
It seems that with inc_warmup==True stan.extract method will save everything but will not tell us which value is a sample or a warmup.
We might still be able to add an extra branch, since the chains are not mixed (when not permuted): 
```python
    # from _misc.pyx
    # the following assumes each chain has same length, same warmup
    cdef int num_warmup = sim['warmup2'][0]

    nth_key = list(sim['samples'][0]['chains'].keys())[n]
    ss = []
    for i in range(num_chains):
        s = sim['samples'][i]['chains'][nth_key]
        if inc_warmup:
            ss.append(s)
        else:
            ss.append(s[num_warmup:])
    return ss
```
we should then be able to do something similar.

**Comment by guiguem** [comment]
In order to have only one wait to interact with the thing, we should always grab the data from permuted==false, the data should appear as 
```python
array([[[ -0.08987545,  12.41256786,  -3.14474384],
        [  0.47863107,   9.26404031,   0.3377154 ],
        [  0.11396987,  10.02314668,   0.80266396],
        [ -1.51834861,  11.97938192,  -3.16816857]],

       [[  0.23406057,  12.23929411,  -2.54433304],
        [ -0.27578248,  10.49558867,   0.61394252],
        [  0.11396987,  10.02314668,   0.80266396],
        [  1.79852815,   8.02517034,  -3.76974028]],

       [[ -0.17177933,  12.09799732,  -2.07941889],
        [  1.06665894,   9.76780957,   0.0739319 ],
        [  0.02504031,   8.69744881,  -0.24666278],
        [  1.32079287,   9.42718559,  -0.47797733]],

       ..., 
       [[  0.19634513,  11.31636865,  -0.29290853],
        [  2.08106148,  10.93753284,  -2.55296991],
        [ -0.55565598,   9.56687308,   0.50678111],
        [ -0.91529824,  12.42375403,  -3.70061134]],

       [[ -1.18979023,   8.67938262,  -1.15541651],
        [ -0.0298548 ,  11.13261525,   0.01520166],
        [ -0.34321047,  10.17445459,   0.72025441],
        [  0.32396397,  11.71602537,  -1.12194535]],

       [[ -0.16115009,   9.34036455,   0.52794209],
        [ -0.0298548 ,  11.13261525,   0.01520166],
        [ -1.17224264,  10.47498465,  -0.18001993],
        [  0.32396397,  11.71602537,  -1.12194535]]])
```
the two first elements of each triplet are the parameters values, the last one might be the log_posterior.
The order of the parameters seems to be as it appears in the model... (will need to find a way to grab the name of each parameter).
Each array of triplet (4) corresponds to the number of chains.
The elements of the array are then the iterations.
We might then have to grab each value for one chain for every iterations, and repeat that for every chain.
A lot of arrays manipulation...

**Comment by guiguem** [comment]
The second point was done in 7b159314cd0db3c91ec08f3838f45bb07d555981

**Comment by guiguem** [comment]
The divergent is an element of StanFit4Model (object return by sampling):
```
get_sampler_params(inc_warmup=True)
Obtain the parameters used for the sampler such as stepsize and treedepth. 
The results are returned as a list, each element of which is an OrderedDict a chain. 
The dictionary has number of elements corresponding to the number of parameters used in the sampler. 
Optional parameter inc_warmup indicates whether to include the warmup period.
```
We might have mode things to grab from it.
Also we will have to
- add the inc_warmup param
- test the nature of the returned object or use the parameter of stan.run.mode #18

**Comment by guiguem** [comment]
One useful diagnostic is the energy difference between steps, in addition to the energy of each sample.

**Comment by joejohnston203** [comment]
#46 adds the 2D plot that colors divergence==0 and divergence==1 points in different colors.
