### ISSUE TITLE
Okay to move "MassHierarchy" input to config file?

### ISSUE THREAD

**Issue by taliaweiss** [project8/morpho#3]
Mathieu – "tritium_neutrino_parameters.data" has a single entry, "MassHierarchy," now that the mixing parameters have been moved to the neutrino mass function file. May I insert "MassHierarchy" as a parameter in the relevant configuration files and delete "tritium_neutrino_parameters.data"?

**Comment by guiguem** [comment]
yes, sounds perfect! 
If you find some parameters which technically will need to be changed on a regular basis, we should put them as parameter of the config file in stan->Data-> parameters...

**Comment by taliaweiss** [comment]
Great – I made that change. Thanks!

**Comment by guiguem** [comment]
Let's close the issue then!
