### ISSUE TITLE
plotting 

### ISSUE THREAD

**Issue by guiguem** [project8/morpho#5]
The idea here is to integrate very generic plotting methods into morpho, which can be called at the end of the post processing.
The each plot will be defined as a dictionary, this the name of the axis, the type of plot (basic one such as histogram, 2D histos, Graph... or more complex such as 2D hits with CL contours...).
This feature might be independently executed (no need of regenerating data from Stan of post processing). 
Some of the plotting methods are already done in the "plotting scripts" in tritium_model

**Comment by jformaggio** [comment]
There is a (potentially outdated) branch of STAN that does visual diagnostics.  Maybe that is sufficient for what you need?

**Comment by guiguem** [comment]
I think this is what Talia used to show that the branches converged, right?
I wanted to do more than that: everyone can add python plotting modules in a folder and then call the method inside these files in the config file to automatically generate plots at the end of the STAN generation (without having to write `python ploting_module.py` after the stan generation), such as convergence diagnosis (as you pointed out) or all the 2D histograms of results of all the possible combinations of the parameters of interest (in order to see correlations between histograms or if distribution are gaussian) or one single 2D plot with confidence intervals... My idea was to make very generic methods which can be parametrized in the config file. But if someone has some plotting methods which is very specific, they can add the file in a folder and use them.

**Comment by taliaweiss** [comment]
To allow me to create useful "analysis" plots on a short-term basis, I included a python script in morpho/examples/MassHierarchy/plotting_scripts (now in develop). It uses the Stan visual diagnostics which Joe mentioned, with input cache and pickle files. This script can be removed once the equivalent functions are integrated into Mathieu's plotting module structure.

**Comment by guiguem** [comment]
Now your plotting script has been added to develop using the plotting feature, we can completely remove scripts files from our "plotting_scripts" folder.

**Comment by taliaweiss** [comment]
Thanks – now done for the MassHierarchy example folder in the develop branch.
