### ISSUE TITLE
Easy cleaning

### ISSUE THREAD

**Issue by guiguem** [project8/morpho#50]
There is a bit of easy cleaning in the bin/morpho we can do, in order to make this more readable.
- [ ] Move the functions into a morpho/tools/tools.py 
- [ ] Move the method using the morpho object into the morpho class

**Comment by joejohnston203** [comment]
Could we potentially move the read_param() method out of the morpho class, into tools.py? It could be a useful method to also have access to in plotting and preprocessing methods.

**Comment by guiguem** [comment]
Indeed. 
In general, any method that does not use the self itself should put outside of the morpho class (and in a separate folder). 
And functions that uses the morpho object should be promoted to methods in the morpho class.

**Comment by guiguem** [comment]
Solved mainly with morpho 2
