### ISSUE TITLE
What does Morpho do, specifically?

### ISSUE THREAD

**Issue by seantalts** [project8/morpho#56]
The README could use some information about Morpho that helps someone decide if they should install it or not. I'm curious to see some use-cases - does it have good automatic plots? Does it have applications outside of physics? Should I be recommending it to generic PyStan users? 

Thanks!

**Comment by guiguem** [comment]
Thanks for the feedback!
Morpho aims at wrapping Stan for convenience and provides some extra features.
A non exhaustive list is given below:
- it reads json/yaml scripts that contains all the details of the simulations: where the model is, what the number of steps or the variables to export are...
- it can import stan functions from external files.
- for each model, morpho creates a cache (in a pkl file) that contains the model to prevent compilations for each sampling of the same model
- it can input and output file formats useful in physics (such as R, root and hdf5) and use the content in the data paragraph: a upcoming upgrade of morpho should allow users to import/export any kind of data files.
- the json script can define a series of actions to perform before and after the stan sampling (such as modifying input data or creating various plots): these actions are defined via python functions and can be imported from the folder morpho/preprocessing (for example) or from any location on the user laptop.

To see some of these features in action, you can execute `morpho --config morpho_test/scripts/morpho_linear_fit.yaml` from the examples folder.

morpho isn't aimed to be physics oriented, so you could indeed recommend it to generic PyStan users.

In the coming weeks, we will have a update of our documentation, this will clarify something and help new users getting started!

**Comment by guiguem** [comment]
@seantalts Hi!
We have updated our documentation, you should have a look at the README in the top directory.
You can find more documentation (with examples on how to use morpho) here: http://www.project8.org/morpho
Please have a look and give us some feedbacks!
Thanks!
