### ISSUE TITLE
Should (minimal) diagnostic info be printed out automatically, or optionally?

### ISSUE THREAD

**Issue by taliaweiss** [project8/morpho#57]
In the develop branch, I added a feature that prints out five lines indicating whether or not your Stan run passed convergence diagnostic tests. These checks are specified by the pyStan workflow described by Mike Betancourt, [here](http://mc-stan.org/users/documentation/case-studies/pystan_workflow.html). A modified version of the [script](https://github.com/betanalpha/jupyter_case_studies/blob/master/pystan_workflow/stan_utility.py) that Mike wrote for that workflow is included in the postprocessing folder.

With this change, when one runs an analysis in morpho, something like this is printed out (immediately after "Result of the sampling"):

[INFO    ] morpho(627) -> Diagnostic info: 
n_eff / iter looks reasonable for all parameters.
Rhat looks reasonable for all parameters.
56.0 of 8000 iterations ended with a divergence (0.7%). Try running with larger adapt_delta to remove the divergences.
0 of 8000 iterations saturated the maximum tree depth of 10. (0%)
E-BFMI indicated no pathological behavior.

Do we want morpho to print out this information automatically (the same way it prints parameter means, Rhat values, etc.)? Automatic printing would encourage the user to take note of and investigate indicators that his or her model did not converge. Alternatively, I could make stan_utility.py into its own postprocessing module that can be called using a line in the config file, like data_reducer.py.

**Comment by guiguem** [comment]
Solved in eca388a51c8bd9aa2c3d21ef7bf8b497f2c80130 !
