### ISSUE TITLE
Rename _Run and _Configure

### ISSUE THREAD

**Issue by joejohnston203** [project8/morpho#88]
Currently, BaseProcessor has Run() and Configure() methods that print some debug statements, then call \_Run() and \_Configure(). \_Run() and \_Configure() are then meant to be overwritten by child classes.

Python style (and resulting docstring parsing programs) dictate that methods starting with "_" are private, and should not be displayed in the public API. However, the \_Run() and \_Configure() methods are the core of morpho2 and should certainly be stored in the public API.

We need to choose new names for the \_Run() and \_Configure() methods that do not start with "_", then rename all \_Run() and \_Configure() methods.

**Comment by guiguem** [comment]
Being addressed by https://github.com/project8/morpho/pull/89

**Comment by guiguem** [comment]
As implemented, the Configure and Run methods are reserved for the BaseProcessorClass.
Any processor needs to derive from this class and implement a InternalConfigure and InternalRun class that are called by the Configure and Run base methods.
